FROM node:latest AS frontend-build
WORKDIR /usr/src/frontend
COPY frontend/ .
RUN npm install
RUN npm run build --configuration=production #build for production


FROM nginx:latest
COPY --from=frontend-build /usr/src/frontend/dist/frontend/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf  
EXPOSE 80

